services:
  - type: worker
    name: temu-shein-bot
    env: python
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python main.py"
    pythonVersion: 3.10.13
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false