# render.yaml
services:
  - type: worker          # ✅ Use worker, not web
    name: shein-temu-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false     # set in Render Dashboard
      - key: DISCORD_ADMIN_ID
        sync: false     # optional
      - key: PROXY_LIST
        sync: false     # multiline value with your proxies
      - key: PROXY_SCHEME
        value: http     # default scheme if not included in proxy lines