services:
  - type: worker
    name: temu-shein-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y git
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      pip install "git+https://github.com/requireCool/pyppeteer-stealth.git@main"
    startCommand: python main.py