services:
  - type: worker
    name: temu-shein-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      pip install git+https://github.com/requireCool/pyppeteer-stealth.git
    startCommand: "python main.py"

